//list of majors that is long af so I moved it to its own file
export const Majors = [
    "Accounting",
    "Advertising",
    "Agriculture",
    "Agricultural and Biological Engineering",
    "Agricultural Business Management",
    "Agriculture Economics",
    "Animal Bioscience",
    "Animal Sciences",
    "Anthropology",
    "Applied Mathematics",
    "Archaeology",
    "Architectural Engineering",
    "Architecture",
    "Art History",
    "Art Education",
    "Biochemistry",
    "Bioengineering",
    "Biology",
    "Biophysics",
    "Biotechnology",
    "Business Administration and Management",
    "Business Logistics",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Science",
    "Crime, Law, and Justice",
    "Earth Sciences",
    "Economics",
    "Electrical Engineering",
    "Elementary and Kindergarten Education",
    "Engineering Science",
    "English",
    "Environmental Systems Engineering",
    "Environmental Sciences",
    "Environmental Resource Management",
    "Film and Video",
    "Finance",
    "Food Science",
    "Forest Science",
    "Forest Technology",
    "General Science",
    "Geography",
    "Geosciences",
    "Graphic Design and Photography",
    "Health and Physical Education",
    "Health Policy and Administration",
    "History",
    "Hotel, Restaurant, and Institutional Management",
    "Human Development and Family Studies",
    "Individual and Family Studies",
    "Industrial Engineering",
    "Information Sciences and Technology",
    "Journalism",
    "Kinesiology",
    "Law Enforcement and Correction",
    "Landscape Architecture",
    "Marine Biology",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Media Studies",
    "Meteorology",
    "Microbiology",
    "Mineral Economics",
    "Modern Languages",
    "Music Education",
    "Nuclear Engineering",
    "Nursing",
    "Nutrition",
    "Philosophy",
    "Physics",
    "Physiology",
    "Political Science",
    "Pre-medicine",
    "Psychology",
    "Public Relations",
    "Real Estate",
    "Recreation and Parks",
    "Rehabilitation Services",
    "Religious Studies",
    "Secondary Education",
    "Sociology",
    "Social Work",
    "Special Education",
    "Speech Communication",
    "Speech Pathology and Audiology/Communication Disorder",
    "Statistics",
    "Telecommunications",
    "Theater",
    "Wildlife and Fishery Science",
  ];
